#!/usr/bin/env bash

journal=$(mktemp journal.XXXXXXXXXX)

trap "rm -r $journal" EXIT

cd "$HOME/$journal_name"
for _file in $(find -name "$@" | sort); do
  echo -e "\n== $_file\n" >> $journal
  cat $_file >> $journal
done
unset _file

. "$HOME/.config/journal/write"
