#!/usr/bin/env bash

date=$(date --date="$@" +%Y/%m/%d)
journal=$(mktemp journal.XXXXXXXXXX)

trap "rm -r $journal" EXIT

cd "$HOME/$journal_name/$date"
for _file in *; do
  echo -e "\n== $_file\n" >> $journal
  cat "$_file" >> $journal
done
unset _file

. "$HOME/.config/journal/write"
