#!/usr/bin/env bash

printf """\
Usage: journal COMMAND { OPTION | help }

COMMAND
  write\t\tUse ${EDITOR:=vim} to edit a page today.
  day\t\tUse ${EDITOR:=vim} to read pages of the specified day.
  consult\tRead journal pages by name in history.
  ls\t\tList all current day pages.
  rm\t\tRemove page(s) of current day.
  any command\tExecute a command in the current day directory.
"""
