#!/usr/bin/env bash

printf """\
Usage: journal COMMAND { OPTION | help }

COMMAND
  write\t\tUse ${EDITOR:=vim} to open a journal page for the current day.
  day\t\tUse ${EDITOR:=vim} to read pages of the specified date.
  consult \tRead journal pages by name in history.
  ls\t\tList all current day pages.
  rm\t\tRemove page(s) of current day.
  any command\tExecute a command in the current day directory.
"""
