#!/usr/bin/env bash

printf """\
Usage: journal { help | COMMAND } [ FILE | DATE ]

COMMAND
  help\t\tGive help message about COMMAND.
  write\t\tUse ${EDITOR:=vim} to edit a page.
  date\t\tUse ${EDITOR:=vim} to read pages of the specified day.
  consult\tRead journal pages by name in history.
  ls\t\tList all current day pages.
  rm\t\tRemove page(s) of current day.
  any command\tExecute a command in the current day directory.
"""
