#!/usr/bin/env bash

editor=${EDITOR:=vim}
journal_name=${JOURNAL_NAME:=saveuriendir}
sep=${JOURNAL_SEP:=/}
command_path=${JOURNAL_PATH:="$HOME/.config/journal/lib"}

if [[ ( -f $command_path/$1 ) ]]; then
  call_mode="$command_path/$1" && shift
elif [[ $(type -t $1) ]]; then
  call_command="$1" && shift
fi

[[ $(date +%-H) -lt 4 ]] && date="yesterday" || date="today"
date=$(date --date=$date +%Y${sep}%m${sep}%d)

[[ $@ ]] && page="${@%%.adoc}.adoc" || page="main.adoc"
page="$(basename ${date}${sep}${page})"

path="$(dirname $HOME/$journal_name/${date}${sep}${page})"
mkdir -p "$path"; cd "$path"

(
if [[ $call_mode ]]; then
  . $call_mode
elif [[ $call_command ]]; then
  $call_command $@
else
  . $command_path/write
fi
)
