#!/usr/bin/env bash

editor=${EDITOR:=vim}
journal_name=${JOURNAL_NAME:=saveuriendir}
command_path="$HOME/.config/journal/lib"

if [[ ( -f $command_path/$1 ) && ( -x $command_path/$1 ) ]]; then
  call_mode="$command_path/$1" && shift
elif [[ $(type -t $1) ]]; then
  call_command="$1" && shift
fi

[[ $(vim --version | grep +clientserver) ]] && socket=true

[[ $(date +%-H) -lt 4 ]] && date="yesterday" || date="today"
date=$(date --date=$date +%Y/%m/%d)

[[ $@ ]] && journal="${@%%.adoc}.adoc" || journal="main.adoc"
journal_path="$HOME/$journal_name/$date/"

mkdir -p "$journal_path"; cd "$journal_path"
if [[ $call_mode ]]; then
  . $call_mode 
elif [[ $call_command ]]; then
  $call_command "$@"
else
  . $command_path/write
fi
