#!/usr/bin/env bash
#
# This file is part of journal.
#
# journal is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# journal is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with journal.  If not, see <https://www.gnu.org/licenses/>.

journal=$(mktemp /tmp/journal.XXXXXXXXXX)

trap "rm -r $page" EXIT

cd "$HOME/$journal_name"
for _file in $(find -name "$@" | sort); do
  echo -e "\n== $_file\n" >> $page
  cat $_file >> $page
done
unset _file

. "$command_path/write"
