#!/usr/bin/env bash

journal=$(mktemp /tmp/journal.XXXXXXXXXX)

trap "rm -r $page" EXIT

cd "$HOME/$journal_name"
for _file in $(find -name "$@" | sort); do
  echo -e "\n== $_file\n" >> $page
  cat $_file >> $page
done
unset _file

. "$command_path/write"
