#!/usr/bin/env bash
#
# This file is part of journal.
#
# journal is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# journal is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with journal.  If not, see <https://www.gnu.org/licenses/>.

date=$(date --date="$@" +%Y${sep}%m${sep}%d)
page=$(mktemp /tmp/journal.XXXXXXXXXX)

trap "rm -r $page" EXIT

cd "$HOME/$journal_name"
for file in $(ls ${date}); do
  echo -e "\n=> $file\n" >> $page
  cat "${date}${sep}$file" >> $page
done

. "$command_path/write"
