#!/usr/bin/env bash
#
# This file is part of journal.
#
# journal is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# journal is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with journal.  If not, see <https://www.gnu.org/licenses/>.

case "$1" in

  ("") printf """\
Usage: journal [help]  { COMMAND } [OPTIONS]

COMMAND
  help\t\tGive help message about COMMAND.
  write\t\tUse \$EDITOR or vim to edit a page.
  date\t\tUse \$EDITOR or vim to read pages of the specified day.
  consult\tRead journal pages by name in history.
  ls\t\tList all current day pages.
  rm\t\tRemove page(s) of current day.
  any command\tExecute a command in the current day directory.
""" ;;

  ("help") printf """\
Usage: journal help [COMMAND]

  Give a short description or help message about the specified COMMAND.
""" ;;

  ("consult") printf """\
Usage: journal consult [NAME]

  search and display all pages matching NAME.
  NAME can be any regexp enclosed by quotes.
""" ;;

  ("write") printf """\
Usage: journal write [NAME]

  create or edit a journal page in current day with \$EDITOR or vim by default.
  If NAME is specified, a new page \`NAME.adoc' now exists. Default name is \`main.adoc'.

  Short form is \`journal [NAME]' where NAME cannot be in \$PATH.
  e.g.: \`journal test' doesn't open the page named \`test.adoc'.
""" ;;

  (*) printf """\
journal: $1: command not found. Try official documentation about command.
""" ;;

esac
